apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xdno5y8l7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xdno5y8l7-python 
  name: xdno5y8l7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xdno5y8l7-python 
